services:
  db:
    image: postgres:18.3
    environment:
      POSTGRES_PASSWORD: shipments@pass
      POSTGRES_USER: app_shipments_user
      POSTGRES_DB: app_shipments_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
