// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShippingOrderService.Web.Domain.Shipments;
using ShippingOrderService.Web.Infrastructure.Persistence;

#nullable disable

namespace ShippingOrderService.Web.Migrations
{
    [DbContext(typeof(ShipmentDbContext))]
    partial class ShipmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "shipment_priority", new[] { "normal", "express", "next_day" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "shipment_status", new[] { "pending", "shipped", "cancelled", "delivered" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShippingOrderService.Web.Domain.Shipments.Shipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("DestinationZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("destination_zip_code");

                    b.Property<string>("OriginZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("origin_zip_code");

                    b.Property<ShipmentPriority?>("Priority")
                        .HasColumnType("shipment_priority")
                        .HasColumnName("priority");

                    b.Property<ShipmentStatus>("Status")
                        .HasColumnType("shipment_status")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("numeric")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("ShippingOrderService.Web.Domain.Shipments.ShipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fragile");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ShipmentId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("shipment_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_shipment_items");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_shipment_items_shipment_id");

                    b.ToTable("shipment_items", (string)null);
                });

            modelBuilder.Entity("ShippingOrderService.Web.Domain.Shipments.ShipmentItem", b =>
                {
                    b.HasOne("ShippingOrderService.Web.Domain.Shipments.Shipment", null)
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_shipment_items_shipments_shipment_id");

                    b.OwnsOne("ShippingOrderService.Web.Domain.Shipments.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<long>("ShipmentItemId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<decimal>("DepthCm")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("dimension_depth_cm");

                            b1.Property<decimal>("HeightCm")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("dimension_height_cm");

                            b1.Property<decimal>("WidthCm")
                                .HasPrecision(8, 2)
                                .HasColumnType("numeric(8,2)")
                                .HasColumnName("dimension_width_cm");

                            b1.HasKey("ShipmentItemId");

                            b1.ToTable("shipment_items");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentItemId")
                                .HasConstraintName("fk_shipment_items_shipment_items_id");
                        });

                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("ShippingOrderService.Web.Domain.Shipments.Shipment", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
